version: '3.6'

services: 
  nginx:
    image: nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - nodeserver
      - vueapp

  nodeserver:
    build: ./nodeserver
    volumes:
      - ./nodeserver:/app
      - /app/node_modules
    environment: 
      - APP_PORT=4000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_USE_POLLING=true
    depends_on: 
      - mongo

  vueapp:
    build: ./vueapp
    volumes:
      - ./vueapp:/app
      - /app/node_modules
    environment: 
      - APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_USE_POLLING=true

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_PASSWORD=root

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    volumes:
      - ./data/mongo:/data/db
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_BASICAUTH_USERNAME=
      - ME_CONFIG_BASICAUTH_PASSWORD=
    depends_on:
      - mongo
    restart: always
